[package]
name = "litentry-substrate-rpc"
version = "0.1.0"
authors = ["zhoujun <junius.zhou@gmail.com>"]
edition = "2018"


[dependencies]
futures-util = "0.2.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0.98"
hyper = "0.12.33"
ureq = { version = "0.11.0", features = ["json"]}
