CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `depost` int(11) NOT NULL AUTO_INCREMENT,
  `round` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 ;

